DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  COLOR VARCHAR(250) NOT NULL,
  BRAND VARCHAR(250) NOT NULL,
  OPERATING_SYSTEM VARCHAR(250) NOT NULL,
  SOLD_BY VARCHAR(250) ,
  PRICE DECIMAL(10, 2),
  AVAILABLE_STOCK INTEGER(10) ,
);

INSERT INTO PRODUCT (NAME, COLOR, BRAND,OPERATING_SYSTEM,SOLD_BY,PRICE,AVAILABLE_STOCK) VALUES
  ('IPhone11', 'White', 'Apple','IOS','Future Mart','78000','10'),
  ('Galaxy M3', 'Black', 'Samsung','Android','Future Mart','17000','12'),
  ('ReadMi', 'Grey', 'MI','Android','Future Mart','8000','17');